name: Deploy React Application

on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker Image Production
              if: contains(github.ref, 'production')
              run: docker build -t puthyporsk0108/book-rental-record-frontend --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}' .
            - name: Build Docker Image Deployment Test
              if: contains(github.ref, 'deployment-test')
              run: docker build -t puthyporsk0108/book-rental-record-frontend-test --build-arg REACT_APP_NODE_ENV='deployment-test' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL_DEPLOYMENT_TEST }}' .
            
            - name: Publish Image to docker hub Production
              if: contains(github.ref, 'production')
              run: docker push puthyporsk0108/book-rental-record-frontend:latest
            - name: Publish Image to docker hub Deployment Test
              if: contains(github.ref, 'deployment-test')
              run: docker push puthyporsk0108/book-rental-record-frontend-test:latest

    deploy:
        needs: build
        runs-on:  self-hosted
        steps:
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Pull image from docker hub Production
              if: contains(github.ref, 'production')
              run: docker pull puthyporsk0108/book-rental-record-frontend:latest
            - name: Pull image from docker hub Deployment Test
              if: contains(github.ref, 'deployment-test')
              run: docker pull puthyporsk0108/book-rental-record-frontend-test:latest

            - name: Delete old container
              run: docker rm -f reactjs-app-container

            - name: Run Docker Container Production
              if: contains(github.ref, 'production')
              run: docker run -d -p 3000:80 --name reactjs-app-container puthyporsk0108/book-rental-record-frontend
            - name: Run Docker Container Deployment Test
              if: contains(github.ref, 'deployment-test')
              run: docker run -d -p 3000:80 --name reactjs-app-container puthyporsk0108/book-rental-record-frontend-test

            - name: Delete old image
              run: docker system prune -f
            
